services:
  - type: web
    name: racing10-lottery
    env: node
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        value: postgresql://bet_game_user:Vm4J5g1gymwPfBNcgYfGCe4GEZqCjoIy@dpg-d0e2imc9c44c73che3kg-a.oregon-postgres.render.com/bet_game
      - key: DB_HOST
        value: dpg-d0e2imc9c44c73che3kg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: bet_game
      - key: DB_USER
        value: bet_game_user
      - key: DB_PASSWORD
        value: Vm4J5g1gymwPfBNcgYfGCe4GEZqCjoIy
    healthCheckPath: /api/game-state
    autoDeploy: true 